import { MapPin, Download, Heart, X, Trash2, Eye } from "lucide-react";
import { useState, useEffect } from "react";
import { wbColleges } from "../../data/wbCollegeData.js";
import CollegeModal from "../components/CollegeModal";

const formatFee = (n) => {
  if (!n) return '—';
  if (n >= 100000) return `₹${(n / 100000).toFixed(1)}L`;
  return `₹${n.toLocaleString('en-IN')}`;
};

const PreferencesList = () => {
  const [selectedCollege, setSelectedCollege] = useState(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [preferences, setPreferences] = useState([]);
  const [filterState, setFilterState] = useState('');
  const [filteredColleges, setFilteredColleges] = useState(wbColleges);

  const CATEGORIES = ['UR', 'EWS', 'OBC', 'SC', 'ST'];
  const STATES = [...new Set(wbColleges.map(c => c.state))].sort();

  useEffect(() => {
    setFilteredColleges(wbColleges);
  }, []);

  const handleSearch = () => {
    let filtered = wbColleges;

    if (filterState) {
      filtered = filtered.filter(c => c.state.toLowerCase().includes(filterState.toLowerCase()));
    }

    setFilteredColleges(filtered);
  };

  const handleAddToPreferences = (college) => {
    if (!preferences.find(p => p.id === college.id)) {
      setPreferences([...preferences, college]);
    }
  };

  const handleRemoveFromPreferences = (collegeId) => {
    setPreferences(preferences.filter(p => p.id !== collegeId));
  };

  const handleReorderUp = (index) => {
    if (index > 0) {
      const newPrefs = [...preferences];
      [newPrefs[index], newPrefs[index - 1]] = [newPrefs[index - 1], newPrefs[index]];
      setPreferences(newPrefs);
    }
  };

  const handleReorderDown = (index) => {
    if (index < preferences.length - 1) {
      const newPrefs = [...preferences];
      [newPrefs[index], newPrefs[index + 1]] = [newPrefs[index + 1], newPrefs[index]];
      setPreferences(newPrefs);
    }
  };

  const handleOpenModal = (college) => {
    setSelectedCollege(college);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setSelectedCollege(null);
  };

  const handleDownloadPDF = () => {
    const prefsText = preferences
      .map((c, i) => `${i + 1}. ${c.name}, ${c.state}`)
      .join('\n');
    
    const element = document.createElement('a');
    const file = new Blob(
      [`PREFERENCE LIST\n\n${prefsText}\n\nGenerated by MedSankalp`],
      { type: 'text/plain' }
    );
    element.href = URL.createObjectURL(file);
    element.download = 'preference-list.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen transition-colors duration-300 bg-[#fffdf7] dark:bg-slate-950 text-[#2d409c] dark:text-white">

      {/* Hero Section */}
      <div className="relative border-b border-amber-200 dark:border-slate-800 bg-linear-to-br from-amber-50 to-amber-100 dark:from-slate-900/60 dark:to-slate-950">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_80%_50%_at_50%_-10%,rgba(249,180,6,0.15),transparent)] dark:bg-[radial-gradient(ellipse_80%_50%_at_50%_-10%,rgba(20,184,166,0.1),transparent)]" />
        <div className="relative max-w-6xl mx-auto px-6 py-16 text-center">
          <h1 className="text-5xl md:text-6xl font-bold tracking-tight mb-4 text-[#2d409c] dark:text-white">
            Find Your <span className="text-[#F9B406] dark:text-teal-400">Colleges</span>
          </h1>
          <p className="text-lg md:text-xl text-[#2d409c] dark:text-slate-400 max-w-3xl mx-auto">
            Build and organize your medical college preferences. Add colleges, reorder them, and download your final list for counselling
          </p>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">

          {/* Left: Filter & Search */}
          <div className="lg:col-span-1">
            <div className="rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 p-6 sticky top-20 h-fit">
              <h2 className="text-xl font-bold mb-6 text-[#2d409c] dark:text-white">Filter Colleges</h2>

              <div className="space-y-5">
                {/* State Filter */}
                <div>
                  <label className="block text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                    State
                  </label>
                  <select
                    value={filterState}
                    onChange={(e) => setFilterState(e.target.value)}
                    className="w-full px-3 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-[#2d409c] dark:text-white focus:outline-none focus:ring-2 focus:ring-[#F9B406] dark:focus:ring-teal-400 text-sm"
                  >
                    <option value="">All States</option>
                    {STATES.map(state => (
                      <option key={state} value={state}>{state}</option>
                    ))}
                  </select>
                </div>

                {/* Search Button */ }
                <button
                  onClick={handleSearch}
                  className="w-full px-4 py-2.5 rounded-lg bg-[#F9B406] dark:bg-teal-400 text-slate-950 font-semibold hover:shadow-lg dark:hover:shadow-teal-500/20 transition-all hover:scale-105"
                >
                  Filter Colleges
                </button>
              </div>

              {/* Stats */}
              <div className="mt-8 pt-8 border-t border-slate-200 dark:border-slate-700">
                <p className="text-sm text-[#2d409c] dark:text-slate-400 mb-3">
                  <span className="font-semibold text-[#2d409c] dark:text-white">{filteredColleges.length}</span> colleges available
                </p>
                <p className="text-sm text-[#2d409c] dark:text-slate-400">
                  <span className="font-semibold text-[#F9B406] dark:text-teal-400">{preferences.length}</span> colleges added to list
                </p>
              </div>
            </div>
          </div>

          {/* Right: Preferences & Colleges */}
          <div className="lg:col-span-3 space-y-8">
            {/* Preference List */}
            <div className="rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 p-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-xl font-bold text-[#2d409c] dark:text-white">Your Preferences</h2>
                {preferences.length > 0 && (
                  <button
                    onClick={handleDownloadPDF}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#F9B406] dark:bg-teal-400 text-slate-950 font-medium text-sm hover:shadow-lg transition-all"
                    title="Download preference list"
                  >
                    <Download className="w-4 h-4" />
                    Download
                  </button>
                )}
              </div>

              {preferences.length > 0 ? (
                <div className="space-y-2 max-h-80 overflow-y-auto scrollbar-visible">
                  {preferences.map((college, index) => (
                    <div key={college.id} className="flex items-start gap-2 p-3 rounded-lg bg-amber-50 dark:bg-teal-500/10 border border-amber-200 dark:border-teal-500/20">
                      <div className="flex items-center justify-center w-6 h-6 rounded-full bg-[#F9B406] dark:bg-teal-400 text-slate-950 dark:text-slate-950 font-bold text-xs shrink-0">
                        {index + 1}
                      </div>
                      <div className="flex-1 min-w-0">
                        <p className="text-sm font-semibold text-[#2d409c] dark:text-white truncate">{college.name}</p>
                        <div className="flex items-center gap-2 mt-1">
                          <p className="text-xs text-[#2d409c] dark:text-slate-400">{college.state}</p>
                          <span className={`text-xs font-medium px-2 py-0.5 rounded-full ${
                            college.management?.toLowerCase() === 'government'
                              ? 'bg-blue-100 dark:bg-blue-500/10 text-blue-700 dark:text-blue-300'
                              : 'bg-purple-100 dark:bg-purple-500/10 text-purple-700 dark:text-purple-300'
                          }`}>
                            {college.management}
                          </span>
                        </div>
                      </div>
                      <div className="flex items-center gap-0.5 shrink-0">
                        <button
                          onClick={() => handleReorderUp(index)}
                          disabled={index === 0}
                          className="p-1 rounded hover:bg-amber-200 dark:hover:bg-teal-500/20 disabled:opacity-30 transition-colors"
                          title="Move up"
                        >
                          ▲
                        </button>
                        <button
                          onClick={() => handleReorderDown(index)}
                          disabled={index === preferences.length - 1}
                          className="p-1 rounded hover:bg-amber-200 dark:hover:bg-teal-500/20 disabled:opacity-30 transition-colors"
                          title="Move down"
                        >
                          ▼
                        </button>
                        <button
                          onClick={() => handleOpenModal(college)}
                          className="p-1 rounded text-blue-500 hover:bg-blue-100 dark:hover:bg-blue-500/10 transition-colors"
                          title="View details"
                        >
                          <Eye className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleRemoveFromPreferences(college.id)}
                          className="p-1 rounded text-red-500 hover:bg-red-100 dark:hover:bg-red-500/10 transition-colors"
                          title="Remove"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-12">
                  <Heart className="w-12 h-12 text-slate-300 dark:text-slate-700 mx-auto mb-3" />
                  <p className="text-slate-500 dark:text-slate-400">
                    Add colleges from the available colleges section below
                  </p>
                </div>
              )}
            </div>

            {/* Available Colleges - Vertical */}
            <div className="rounded-2xl bg-white dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 p-6">
              <h2 className="text-xl font-bold mb-6 text-[#2d409c] dark:text-white">Available Colleges</h2>
              <div className="overflow-y-auto max-h-96">
                <div className="flex flex-col gap-3 scroll-auto">
                  {filteredColleges.length > 0 ? (
                    filteredColleges.map((college) => {
                      const isAdded = preferences.some(p => p.id === college.id);
                      return (
                        <div key={college.id} className="flex flex-col p-4 rounded-lg border border-slate-200 dark:border-slate-700 hover:border-amber-200 dark:hover:border-teal-500/30 transition-colors bg-slate-50 dark:bg-slate-800/50">
                          <div className="flex items-start justify-between gap-2 mb-3">
                            <div className="flex-1 min-w-0">
                              <p className="text-sm font-semibold text-[#2d409c] dark:text-white">{college.name}</p>
                            </div>
                            {!isAdded ? (
                              <button
                                onClick={() => handleAddToPreferences(college)}
                                className="p-2 rounded-lg bg-amber-100 dark:bg-teal-500/10 text-[#F9B406] dark:text-teal-400 hover:bg-amber-200 dark:hover:bg-teal-500/20 transition-colors shrink-0"
                                title="Add to preferences"
                              >
                                <Heart className="w-5 h-5" />
                              </button>
                            ) : (
                              <button
                                onClick={() => handleRemoveFromPreferences(college.id)}
                                className="p-2 rounded-lg bg-red-100 dark:bg-red-500/10 text-red-500 dark:text-red-400 hover:bg-red-200 dark:hover:bg-red-500/20 transition-colors shrink-0"
                                title="Remove from preferences"
                              >
                                <Heart className="w-5 h-5 fill-current" />
                              </button>
                            )}
                          </div>
                          <div className="flex flex-col gap-2">
                            <p className="text-xs text-[#2d409c] dark:text-slate-400">{college.state}</p>
                            <span className={`text-xs font-medium px-2 py-1 rounded-full inline-block w-fit ${
                              college.management?.toLowerCase() === 'government'
                                ? 'bg-blue-100 dark:bg-blue-500/10 text-blue-700 dark:text-blue-300'
                                : 'bg-purple-100 dark:bg-purple-500/10 text-purple-700 dark:text-purple-300'
                            }`}>
                              {college.management}
                            </span>
                          </div>
                        </div>
                      );
                    })
                  ) : (
                    <p className="text-sm text-slate-500 dark:text-slate-400 py-8">No colleges match your filters</p>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <CollegeModal college={selectedCollege} isOpen={isModalOpen} onClose={handleCloseModal} />
    </div>
  );
};

export default PreferencesList;
